AWSTemplateFormatVersion: 2010-09-09
Description: Deployment of EFS
Resources:
  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable TCP access via port 2049
      SecurityGroupIngress:
        - CidrIp:
            !ImportValue network:VPCCIDR
          FromPort: '2049'
          IpProtocol: tcp
          ToPort: '2049'
      VpcId: !ImportValue network:VPC
  EFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: EFS
      PerformanceMode: generalPurpose
      BackupPolicy:
        Status: ENABLED
  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS
      SubnetId: !ImportValue network:PublicSubnet1
      SecurityGroups:
        - !Ref EFSSecurityGroup
  MountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS
      SubnetId: !ImportValue network:PublicSubnet2
      SecurityGroups:
        - !Ref EFSSecurityGroup
  MountTarget3:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFS
      SubnetId: !ImportValue network:PrivateSubnet2
      SecurityGroups:
        - !Ref EFSSecurityGroup
           
Outputs:
  EFS:
    Description: Reference to the EFS instance
    Value: !Ref EFS
    Export:
      Name: EFS
  MountTargetDNS1:
    Description: DNS name of the EFS mount target
    Value: !GetAtt MountTarget1.IpAddress
    Export:
      Name: MountTargetDNS
  MountTargetDNS2:
    Description: DNS name of the EFS mount target
    Value: !GetAtt MountTarget2.IpAddress
    Export:
      Name: MountTargetDNS2
