AWSTemplateFormatVersion: 2010-09-09
Description: Deployment of RDS - Microsoft SQL Server
Parameters:
  username:
    Type: String
    Description: The master username for the RDS instance
    Default: admin
  password:
    Type: String
    Description: The master password for the RDS instance
    Default: MySecurePassword123
Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable TCP access via port 1433
      SecurityGroupIngress:
        - CidrIp:
            !ImportValue network:VPCCIDR
          FromPort: '1433'
          IpProtocol: tcp
          ToPort: '1433'
      VpcId: !ImportValue network:VPC
      SecurityGroupEgress: []  # Deny all outbound traffic
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !ImportValue network:PrivateSubnet1
        - !ImportValue network:PrivateSubnet2
      Tags:
        - Key: Name
          Value: SubnetGroup
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.small
      MonitoringInterval: 0
      AvailabilityZone: !ImportValue network:AvailabilityZone1
      BackupRetentionPeriod: 0 
      DBInstanceIdentifier: webappdb 
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: sqlserver-web
      LicenseModel: license-included
      MasterUsername: !Ref username
      MasterUserPassword: !Ref password
      MultiAZ: false
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      Tags:
        - Key: Name
          Value: RDSInstance
Outputs:
  DBInstance:
    Description: Reference to the RDS instance
    Value: !Ref DBInstance
    Export:
      Name: DBInstance
  DBEndpoint:
    Description: Endpoint of the RDS instance
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: DBEndpoint
  username:
    Description: Username for the RDS instance
    Value: !Ref username
    Export:
      Name: DBUsername
  password:
    Description: Password for the RDS instance
    Value: !Ref password
    Export:
      Name: DBPassword