AWSTemplateFormatVersion: 2010-09-09
Description: Deployment of S3 Bucket with Static Website
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-s3-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false  
        BlockPublicPolicy: false  
        IgnorePublicAcls: false 
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-s3-bucket"
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: Name of the S3 bucket
  S3BucketWebsiteURL:
    Value: !Sub "http://${S3Bucket}.s3-website-${AWS::Region}.amazonaws.com"
    Description: URL of the static website
