AWSTemplateFormatVersion: 2010-09-09
Description: Deployment of S3 Bucket with Lambda Trigger
Resources:
  FileUploadLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: trigger.handler
      Role: arn:aws:iam::<id>:role/LabRole
      FunctionName: FileUploadProcessor
      Runtime: nodejs18.x 
      Code:
        S3Bucket: !ImportValue S3Moszynski
        S3Key: trigger.zip 
      Timeout: 60

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref FileUploadLambda
      Principal: s3.amazonaws.com
      SourceArn: !ImportValue S3MoszynskiArn
Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt FileUploadLambda.Arn