AWSTemplateFormatVersion: 2010-09-09
Description: Deployment of S3 Bucket for Storing Lambda Code and Exports
Resources:
  S3BucketForZip:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-s3-bucket"
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-s3-bucket"
Outputs:
  S3BucketName:
    Description: The name of the S3 bucket
    Value: !Ref S3BucketForZip
    Export:
      Name: S3Moszynski
  S3BucketArn:
    Description: The ARN of the S3 bucket
    Value: !GetAtt S3BucketForZip.Arn
    Export:
      Name: S3MoszynskiArn
